training:
  architecture: DoubleDQN
  device: mps
  environment_id: PongNoFrameskip-v4
  learning_rate: 0.00025
  gamma: 0.99
  batch_size: 128
  target_update: 5000
  buffer_type: ExperienceBuffer # ExperienceBuffer or PERBuffer
  buffer:
    min_buffer_size: 5000
    buffer_capacity: 100000
  per_buffer:             # Only for PERBuffer
    min_priority: 0.1
    alpha: 0.6
    beta: 0.4 
    beta_growth: 1.00005
    per_update: 20
  max_episodes: 2500
  max_steps_per_episode: 10000
  epsilon:
    start: 1.0
    end: 0.02
    decay: 0.995
  verbose: true
  use_wandb: true
  wandb_config:
    entity_name: sorenjmadsen # Replace with your own entity name for Weights & Biases
evaluation:
  device: cuda
  environment_id: PongNoFrameskip-v4
  weights_path: checkpoints/replay-checkpoint.pth